### ISSUE TITLE
(Lack of )whitespace in short tags

### ISSUE THREAD

**Issue by pihentagy** [renggli/dart-xml#109]
When not modifying the file, the printed string is different (note the lack of space after `watch-this`.

It bothers me, because I operate on files I do not own, just would like to make some light transformations.

```dart
  final bookshelfXml = '''<?xml version="1.0"?>
    <bookshelf>
      <watch-this />
      <!-- comments are welcome --><!-- and also PRs -->

    </bookshelf>''';
  final document = XmlDocument.parse(bookshelfXml);
  print(document.toString());
```

```xml
<?xml version="1.0"?>
    <bookshelf>
      <watch-this/>
        <!-- comments are welcome --><!-- and also PRs -->

    </bookshelf>
```

**Comment by renggli** [comment]
Whitespaces within tags (after the tag-name, between attributes, and before the closing `>` or `/>`) are not significant. While it would be possible to preserve them for some transformations, it adds quite a bit of complexity to the code. I am not aware of any XML library that would do this?

**Comment by rspilker** [comment]
I do recognize that a lot of XML does contain one space character in that location.

Instead of preserving the actual white space, wouldn't it be lightweight to add a parameter for the `XmlPrettyWriter` to insert one space for a closed element?

@renggli  I can easily create a pull request if you're likely to accept it. If you want that, please tell me if you would like a `bool` parameter or a `Predicate<XmlNode>?`, and what you think would be a good name. Maybe `spaceBeforeSelfClosing`?

**Comment by renggli** [comment]
Yeah, a predicate on the `XmlNode` would make sense.

**Comment by rspilker** [comment]
Uhm, can you explain what you mean by "we don't want to limit to self-closing elements?"

As I understand a self-closing element is an element without text or children. Like `<watch-this/>` or `<watch name="movie"/>`. And the idea is to optionally write `<watch-this />` or `<watch name="movie" />`. Am I missing a scenario where you would also like to inset an extra space?

**Comment by renggli** [comment]
I was thinking maybe somebody wants `<watch name="movie" >` or `</watch >`, but that looks really odd. Your proposal pull request looks great.
