### ISSUE TITLE
Expose XmlPrettyPrinter

### ISSUE THREAD

**Issue by rspilker** [renggli/dart-xml#55]
Since the rewrite of the package structure, the XmlPrettyPrinter has moved, breaking my code.

I suggest to expose it from xml.dart, to prevent future breakage.

**Comment by renggli** [comment]
Sorry about that. It was not intentional that all the internal packages were exposed and I've tried to fix this with 3.3.0, however this introduced problems for a few people like you that depended on these packages. I've exposed `XmlWriter` and `XmlPrettyPrinter` in 6e6547a813eea0aa42774dd87849b32b03f03da0 and released 3.3.1 on pub.
